telegram:
  api-url: "https://api.telegram.org/"
  bot-name: "TG Premium"
  bot-uri: ""
  bot-token: "key"
message:
  start-message: "hello!"
  too-big-voice:
    text: "текст сообщения в ответ на отправку слишком длинного голосового сообщения (лимит - 10 минут)"
  illegal-message:
    text: "illegal message!"
  wtf:
    text: "wtf"
commands:
  start-command: "/start"
assembly-ai:
  api-key: "key"
